env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/react-in-jsx-scope:
    - off
  '@typescript-eslint/no-unused-vars':
    - error
