version: "3.9"
services:
  client:
    image: ${APP_NAME}_client
    build:
      context: ./client
    container_name: ${APP_NAME}_client
    command: pnpm prod
    restart: unless-stopped
    environment:
      - VITE_PORT=${CLIENT_PORT}
      - VITE_HMR_PORT=${CLIENT_HMR_PORT}
    networks:
      - common

  server:
    image: ${APP_NAME}_server
    build:
      context: ./server
    container_name: ${APP_NAME}_server
    command: pnpm start:prod
    restart: unless-stopped
    environment:
      - PORT=${SERVER_PORT}
    networks:
      - common

  nginx:
    image: ${APP_NAME}_nginx
    build:
      context: ./nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - common

networks:
  common:
    name: ${APP_NAME}-network
    driver: bridge
