version: "3.9"
services:
  ui:
    image: ${APP_NAME}_ui
    build:
      context: ./ui
    container_name: ${APP_NAME}_ui
    command: npm run deploy
    restart: unless-stopped
    networks:
      - common

  api:
    image: ${APP_NAME}_api
    build:
      context: ./api
    environment:
      - PORT=${API_PORT}
    container_name: ${APP_NAME}_api
    command: npm run deploy
    restart: unless-stopped
    networks:
      - common

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
      - ui
    networks:
      - common

networks:
  common:
    name: ${APP_NAME}-network
    driver: bridge
