version: "3.9"
services:
  client:
    command: pnpm dev
    stdin_open: true
    tty: true
    ports:
      - ${CLIENT_HMR_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/usr/src/app/src

  server:
    command: pnpm start:dev
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/dist:/usr/src/app/dist

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
