version: "3.9"
services:
  ui:
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./ui/src:/usr/src/app/src

  api:
    command: npm run start:dev
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/test:/usr/src/app/test
