env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
